name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.1", "8.2", "8.3" ]
        composer_flags: [ "", "--prefer-lowest" ]
    name: 'Build & validate: PHP ${{ matrix.php }} ${{ matrix.composer_flags}}'
    env:
      PHP: ${{ matrix.php }}
      COMPOSER_MEMORY_LIMIT: -1
      COMPOSER_FLAGS: ${{ matrix.composer_flags }}
      PHP_VERSION: ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xdebug, zip
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
      - name: Static analysis with PHPStan
        run: composer checktype
      - name: Coding style PSR12 Check
        run: composer checkstyle
      - name: Execute tests (Unit and Feature)
        run: composer test-report
      - name: Run SonarCloud scanner
        uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/sonarcloud@main
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
